# Generated by Django 3.2.4 on 2022-04-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('first_number', models.CharField(max_length=30)),
                ('second_number', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('inlineRadioOptions', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=30)),
                ('classe', models.CharField(max_length=30)),
                ('info_sup', models.CharField(max_length=30)),
            ],
        ),
    ]
